#
movement_config: 'tank_steering'

#related to the movement_config
motor_left: 'left_epos2'
motor_right: 'right_epos2'

#related to the motors
left_epos2:
   #must be set for every motor
   motor_plugin: 'modrin_motor_plugins::Epos2'
   #information requested by the motor driver itself
   node_nr: 2
   reverse: false
   port: 'USB0'
   baudrate: 1000000
   timeout: 850

right_epos2:
   #must be set for every motor
   motor_plugin: 'modrin_motor_plugins::Epos2'
   #information requested by the motor driver itself
   node_nr: 1
   reverse: true
   can_connected_with: 'left_epos2'
