#related to the hardware of the robot
movement_config: 'tank_steering'
wheels_tf: ['left_epos2', 'right_epos2']

#related to the config of the wheels
left_epos2:
   #indicates if a motor or a encoder is connected to this wheel
   motor_plugin: 'modrin_motor_plugins::Epos2'
   encoder_plugin: 'modrin_encoder_plugins::Epos2'
   #information requested by the plugins themselves
   node_nr: 2
   port: 'USB0'
   baudrate: 1000000   #[Bits/s]
   timeout: 850   #[ms]
   motor_reverse: false

   motor_type: 1  #1: brushed DC motor; 10: EC motor sinus commutated; 11: EC motor block commutated
   motor_nominal_current: 5770   #[mA]
   motor_max_output_current: 12000  #[mA]
   motor_max_rpm: 9000  #[rev/min]
   motor_thermal_time_constant: 1000  #[ms]
   #motor_pole_pair_number: 2 #[1] only for EC motors

right_epos2:
   #indicates if a motor or a encoder is connected to this wheel
   motor_plugin: 'modrin_motor_plugins::Epos2'
   encoder_plugin: 'modrin_encoder_plugins::Epos2'
   #information requested by the plugins themselves
   node_nr: 1
   can_connected_with: 'left_epos2'
   motor_reverse: true

   motor_type: 1  #1: brushed DC motor; 10: EC motor sinus commutated; 11: EC motor block commutated
   motor_nominal_current: 5770   #[mA]
   motor_max_output_current: 12000  #[mA]
   motor_max_rpm: 9000  #[rev/min]
   motor_thermal_time_constant: 1000  #[ms]
   #motor_pole_pair_number: 2 #[1] only for EC motors
